import { Poppins } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/layout/Topbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  // variable: "--font-poppins",
});

export const metadata = {
  title: "Myxellia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  font-poppins  text-[12px] text-[#3D3D3D]`}
      >
        <Topbar />
        <div className="lg:px-[78px] px-5 ">{children}</div>
      </body>
    </html>
  );
}
